# Generated by Django 4.0.3 on 2022-05-23 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='desciption',
            new_name='description',
        ),
    ]
